[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.18'
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
goerli = "${GOERLI_ARB_RPC_URL}"
bsctest = "${BSCTEST_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
bsctest = { key = "${BSCSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config